### ISSUE TITLE
QA UnionML docs

### ISSUE THREAD

**Issue by cosmicBboy** [unionai-oss/unionml#67]
go through UnionML docs and make sure:
- code and instructions work
- copy reads well

**Comment by cosmicBboy** [comment]
@marc-union just made this issue for QA'ing docs here on the unionoss roadmap.

Currently this is blocked by v0.2.0 beta release, which should be out by tomorrow

**Comment by marc-union** [comment]
@cosmicBboy Here is my 1st set of comments:

Quick Start
-----------

https://unionml.readthedocs.io/en/latest/

- General: Excellent quick start. Compact, straightforward, demonstrates key concepts quickly.

- Suggestion: "starting with model training and offline and online prediction." -> "starting with model training and both offline and online prediction." Or -> "starting with model training and prediction, both offline and online." Rationale: Too many "and"s.

- Suggestion: Be consistent about "UnionML". Is it "UnionML" or `unionml`?


Installation
------------

https://unionml.readthedocs.io/en/latest/index.html#installation

- Minimum or required version of Python?

- which ML frameworks are included? sklearn? Pytorch and keras don't seem to be included in UnionML's dependencies, which causes errors described below. Does it make sense to recommend installing pytorch or keras?

- Which parts of Flyte does UnionML depend on? `flytekit`? If yes, say so.

- numpy on Apple M1 seems to break the installation. Mention a workaround? This page shows a workaround: https://tilcode.blog/2021/06/14/how-to-install-numpy-and-pandas-for-data-science-in-a-m1-macbook/

- also on M1: pip install tensorflow-macos is broken because of h5py. This page shows a workaround: https://stackoverflow.com/questions/66741778/how-to-install-h5py-needed-for-keras-on-macos-with-m1
  

Quick Start
-----------

https://unionml.readthedocs.io/en/latest/index.html#quickstart

- Suggestion: rewrite heading "A Minimal UnionML App" as a para. Something like "This example shows you how to create a minimal UnionML App with sklearn, pytorch, or keras." Rationale: Be clear about the frameworks in this quick start, especially since the rest of the example code in the doc uses only sklearn.

- Suggestion: examples include pytorch and keras. Add CLI commands for installing them?

- Suggestion: Tell the user to put this example code in a file named `main.py`.

https://unionml.readthedocs.io/en/latest/index.html#define-app-methods

Suggestion: Be more prescriptive, less descriptive. "The dataset and model objects expose decorators..." -> "Specify your core functions for training and prediction with the decorators from `dataset` and `model`:"

Question: What do you mean by "core components?" What else can we decorate besides Python functions?



https://unionml.readthedocs.io/en/latest/index.html#train-and-predict-locally

- For the sklearn, torch, and keras examples, I get a similar error:

```
if __name__ == "__main__":
    model_object, metrics = model.train(hyperparameters={"C": 1.0, "max_iter": 100})
    predictions = model.predict(features=load_digits(as_frame=True).frame.sample(5, random_state=42))
    print(model_object, metrics, predictions, sep="\n")
```

Error:

```
% python main.py
/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
```

Increasing `max_iter` prevents this error:

```
    model_object, metrics = model.train(hyperparameters={"C": 1.0, "max_iter": 5000})
```
  
- I also get this error for torch when using the example for sklearn:

```
(union-ai-oss-67) marc@Marcs-MBP quickstart-sklearn % python main.py
LogisticRegression(max_iter=5000.0)
{'train': 1.0, 'test': 0.9722222222222222}
[6.0, 9.0, 3.0, 7.0, 2.0]
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    model.save("/tmp/model_object.joblib")
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/model.py", line 388, in save
    return self._saver(self.artifact.object, self.artifact.hyperparameters, file, *args, **kwargs)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/model.py", line 525, in _default_saver
    import torch
ModuleNotFoundError: No module named 'torch'
```

Installing torch manually fixes the error:

```
(union-ai-oss-67) marc@Marcs-MBP quickstart-sklearn % pip install torch
Collecting torch
  Downloading torch-1.11.0-cp38-none-macosx_11_0_arm64.whl (43.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 24.8 MB/s eta 0:00:00

Requirement already satisfied: typing-extensions in /Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages (from torch) (4.2.0)
Installing collected packages: torch
Successfully installed torch-1.11.0
(union-ai-oss-67) marc@Marcs-MBP quickstart-sklearn % python main.py
python main.py
LogisticRegression(max_iter=5000.0)
{'train': 1.0, 'test': 0.9722222222222222}
[6.0, 9.0, 3.0, 7.0, 2.0]
(union-ai-oss-67) marc@Marcs-MBP quickstart-sklearn % cd ../quickstart-pytorch
(union-ai-oss-67) marc@Marcs-MBP quickstart-pytorch % python main.py
python main.py
PytorchModel(
  (layers): Sequential(
    (0): Linear(in_features=64, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=10, bias=True)
  )
)
{'train': 0.7682672233820459, 'test': 0.7388888888888889}
[6.0, 8.0, 3.0, 7.0, 2.0]
(union-ai-oss-67) marc@Marcs-MBP quickstart-pytorch % 
```

- Output from keras example code has some warnings and an error:

```
(union-ai-oss-67) marc@Marcs-MBP quickstart-keras % python main.py
python main.py
2022-05-16 17:19:01.410059: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/100
3/3 [==============================] - 0s 3ms/step - loss: 17.2853 - accuracy: 0.0738

...

Epoch 100/100
3/3 [==============================] - 0s 13ms/step - loss: 0.9150 - accuracy: 0.6841
2022-05-16 17:19:02.929798: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
<keras.engine.sequential.Sequential object at 0x16b50e910>
{'train': 0.6875434933890049, 'test': 0.6833333333333333}
[6.0, 9.0, 3.0, 9.0, 2.0]
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    model.save("/tmp/model_object.h5")
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/model.py", line 388, in save
    return self._saver(self.artifact.object, self.artifact.hyperparameters, file, *args, **kwargs)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/model.py", line 539, in _default_saver
    raise NotImplementedError(
NotImplementedError: Default saver not defined for type <class 'keras.engine.sequential.Sequential'>. Use the Model.saver decorator to define one.
(union-ai-oss-67) marc@Marcs-MBP quickstart-keras %
```


Serve Seamlessly with FastAPI
=============================

https://unionml.readthedocs.io/en/latest/index.html#serve-seamlessly-with-fastapi


- Question: Where should this example code go? Should you show how to refactor `main.py` to use this example code for setting up FastAPI? Maybe get rid of the `__main__` guard?

- Suggestion: Tell the user to add client code ("Then you can invoke the endpoints...") in a file named something like `client.py`.

- I get this error from my UnionML app when I try to request from it:


```
(union-ai-oss-67) marc@Marcs-MBP quickstart-pytorch % unionml serve main:app --reload --model-path /tmp/model_object.pt

INFO:     Will watch for changes in these directories: ['/Users/marc/Documents/union-ai-oss-67/quickstart-pytorch']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [16597] using statreload
PytorchModel(
  (layers): Sequential(
    (0): Linear(in_features=64, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=10, bias=True)
  )
)
{'train': 0.5915100904662491, 'test': 0.6083333333333333}
[6.0, 3.0, 3.0, 7.0, 3.0]
INFO:     Started server process [16602]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:58305 - "POST /predict HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/fastapi.py", line 59, in predict
    model.artifact = get_latest_model_artifact(model, version)
  File "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/remote.py", line 105, in get_latest_model_artifact
    raise RuntimeError("You need to configure the remote client with the `Model.remote` method")
RuntimeError: You need to configure the remote client with the `Model.remote` method
```

**Comment by marc-union** [comment]
@cosmicBboy 2nd set of comments:



Deployment Guide
----------------

https://unionml.readthedocs.io/en/latest/deploying.html

- General: Well done again. Concise, clear, straightforward.

- Suggestion: Be consistent about "UnionML". Is it "UnionML" or `unionml`?

- Typos: Make sure that names in links correctly match the headings they link to. Examples: "Deploy to a Flyte Cluster" links to "Deploying to Flyte", "Serve with FastAPI" links to "Serving with FastAPI"

- Suggestion: "Currently, UnionML apps support two core types of machine learning microservices..." -> "You can create UnionML apps to provide microservices for model training and model serving." Rationale: rephrase to describe what the user can do.
  

Production Backend Deployment
=============================

https://unionml.readthedocs.io/en/latest/deploying.html#production-backend-deployment

- Suggestion: rename title for consistency with other titles and to guide the user more clearly. "Production Backend Deployment" -> something like "Deploying a Production Backend" or "Deploying to Production"

- Suggestion: Break 2 (important) sentences into 2 sentences. "unionml uses flytekit under the hood to execute..." -> "UnionML uses `flytekit` under the hood... workflows locally. And you can benefit from the..."

- Terminology: "workflow" makes its first appearance here but isn't defined. Do you want to use Flyte terminology (tasks, workflows, etc) or stick with UnionML terminology (models, data)? I suggest sticking w/the latter.
  

Serving Predictions
===================

https://unionml.readthedocs.io/en/latest/deploying.html#serving-predictions

- Incorrect: "Once you have a trained model object that you want to serve in production, you can." The user isn't serving the model, the user is setting up a model to serve clients. Also, I suggest making it clear that this is a deployed model, not a local model.

- Suggestion: "Once you have a deployed model, you can set it up to serve predictions:"


Deploying to Flyte
------------------

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#deploying-to-flyte

- Suggestion: Demote the note "In the previous guides" to a plain para. There's nothing exceptional or unintuitive about its info that requires an admonishment.
  
- Suggestion: This intro is mostly redundant. Delete text before "In the previous guides, " and start the intro with this para ("In the previous guides...")

- Suggestion: Repetitive. In "UnionML integrates tightly with Flyte..." delete "data- and machine-learning-aware orchestration"

- Suggestion: Style guide recommends bullet lists, not numbered, for lists that are not in task steps. In other words, this list is a summary, not a set of steps that the user must follow.

- Suggestion: Revise the bullet list or retitle the subsequent headings so that they are consistent. For example, the list item "Spin up a demo Flyte cluster" doesn't have an obvious, easy-to-find corresponding section in this page.


  
Prerequisites
=============

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#prerequisites

Install Docker and make sure you have the Docker daemon running.


Deploy App Workflows
====================

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#deploy-app-workflows

- Suggestion: Is this a tutorial (the digits classification app) or a description of the concepts & techniques for deploying a unionml model? Choose a lane and stick to it. If this is a tutorial then call it that and proceed accordingly. If this is a description of the concepts and tasks needed to deploy any unionml model, then use the digits classification app as an example when needed.

- Suggestion: The sub-sections in this section don't quite guide the user through a progressive sequence. The intro of this page promises that "we'll need cloud services" but this section deals exclusively with the flytectl demo and punts actual cloud deployment to the Flyte doc. Would it make sense to make it clearer that the path to cloud deployment is best done by starting locally?
  
- Terminology: You use "workflow" without defining it first but isn't hiding Flyte's more sophisticated/advanced features one of UnionML's features? In other words, you're assuming that the user of a layer above Flyte already knows Flyte. :P

- Suggestion: move the paras ("A UnionML app is composed of a" and "To make these computations scalable,") to the intro of this page.


Initializing a Digits Classification App
========================================

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#initializing-a-digits-classification-app

- Suggestion/question: Is the user initializing an app? Or creating a new one? "Initializing" seems inaccurate here. How about this title instead: "Create your app"? Then describe what the app must provide. Only then use the digits classification app as an example. (Or flip these if you take the tutorial lane.)

- Error: `unionml init my_app` breaks on my machine with unionml 0.02. `cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/Users/marc/Documents/union-ai-oss-67/lib/python3.8/site-packages/unionml/templates/basic" could not be found in the following locations:
`





UnionML CLI
===========

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#unionml-cli

- Suggestion: move to its own page in the Deployment Guide?


Programmatic API
================

https://unionml.readthedocs.io/en/latest/flyte_cluster.html#programmatic-api

- Suggestion: move to its own page in the Deployment Guide?

**Comment by cosmicBboy** [comment]
thanks for the comprehensive review!

> Suggestion: Be consistent about "UnionML". Is it "UnionML" or unionml?

I already did a find-replace on this... which ones did I miss?

> Typos: Make sure that names in links correctly match the headings they link to. Examples: "Deploy to a Flyte Cluster" links to "Deploying to Flyte", "Serve with FastAPI" links to "Serving with FastAPI"

I don't think this necessarily has to be so... I think it's fine to re-word the heading to fit in the context of the sentence that's linking to a page.

> Terminology: "workflow" makes its first appearance here but isn't defined. Do you want to use Flyte terminology (tasks, workflows, etc) or stick with UnionML terminology (models, data)? I suggest sticking w/the latter.

I think we'll want to link the flyte workflows page here. We're talking about Flyte in the deployment guide, so I think we need to start introducing the terminology here.

> Incorrect: "Once you have a trained model object that you want to serve in production, you can." The user isn't serving the model, the user is setting up a model to serve clients. Also, I suggest making it clear that this is a deployed model, not a local model.

Not sure I understand this point. I get the technicality, but I think it's fine to use "serve" as a verb where the user is the subject, tho the suggestion is fine I think.

> Suggestion: move to its own page in the Deployment Guide?

For the UnionML CLI and Programmatic API, we do eventually want a proper CLI and API reference https://github.com/unionai-oss/unionml/issues/71. This will probably live in another section in the docs.

In the context of the deployment guide I think it's appropriate where it is, since it  ties directly with the commands needed for the user to test the deployment.

The rest of the editorial suggestions LGTM, we should open up a `team-beacon` ticket (or maybe tickets per page?) so folks can pick them up.
